name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '14'
            - uses: pnpm/action-setup@v1.2.1
              with:
                  version: 5.3.0
                  run_install: |
                      - args: [--frozen-lockfile, --strict-peer-dependencies]
            - name: build
              run: npm run-script build
            - uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: ./out/
