name: test

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: '14'
            - uses: pnpm/action-setup@v1.2.1
              with:
                  version: 5.12.0
                  run_install: |
                      - args: [--frozen-lockfile, --strict-peer-dependencies]
            - name: test
              run: npm test
            - uses: codecov/codecov-action@v1
              with:
                  file: ./coverage/coverage-final.json
